# fly.toml app configuration file generated for comparapp-hidden-sound-753 on 2025-01-11T14:48:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comparapp-hidden-sound-753'
primary_region = 'gig'

[build]
  image = "python:3.9"  # Corrigido o formato correto para build

[env]
  PORT = '5000'

[[services]]
  internal_port = 5000
  
  [[services.ports]]
    handlers = ["http"]
    port = 80  # Porta pública usada para acessar o app

# Seção [http_service] removida para evitar conflito com [[services]]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
